admin_product:
    resource: "@FormationAdminBundle/Controller/"
    type:     annotation
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
