<?php

namespace Formation\CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectLogRepository extends EntityRepository
{
}

