<?php

namespace Formation\CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findProductsByCategory($categoryId)
    {
        $qb = $this->createQueryBuilder('p')
             ->innerJoin('p.categories', 'c')
             ->where('c.id = ?1')
             ->setParameter('1', $categoryId);
        
        return $qb->getQuery()->getResult();
    }
}
