page_homepage:
    path:     /{_locale}
    defaults: { _controller: PageBundle:Front:index, _locale: "%locale%" }
    requirements:
        _locale: en|fr
        
page_category:
    path:    /{_locale}/category/{id}
    defaults: { _controller: PageBundle:Front:category, _locale: "%locale%" }
    requirements:
        _locale: en|fr
        
page_product:
    path:    /{_locale}/category/{categoryId}/product/{productId}
    defaults: { _controller: PageBundle:Front:product, _locale: "%locale%" }
    requirements:
        _locale: en|fr
